### ISSUE TITLE
ユーザー区分

### ISSUE THREAD

**Issue by coord-e** [sohosai/sos21-backend#13]
学部生、院生、教員を区別する。

`UserCategory` モデルを追加し、 `User` モデルの `category` フィールドに持たせる。
それぞれの層の DTO を修正し、エンドポイントまで `category` が届くようにする。
`create_user` `update_user` などの入力で `category` を受け取るようにし、同様に `signup` などの入力でも受け取るように修正する。また、`export_users` で区分をエクスポートするようにする。

**Comment by azarashi2931** [comment]
ユーザの区分は単に/signup APIで受け取る(入力を信頼する)だけでよい？

**Comment by azarashi2931** [comment]
@coord-e

**Comment by coord-e** [comment]
ok
