### ISSUE TITLE
関われる企画を1つに制限する

### ISSUE THREAD

**Issue by mkobayashime** [sohosai/sos21-backend#22]
総務の意向もあり、1人の人間が責任者または副責任者として関われる企画は最大1つに制限される

- 企画登録時(`project/create`)に当該ユーザーが他に関わっている企画が存在するかチェックし、存在する場合にはエラーを出して企画登録を行わない
- `me/project/list`は複数あることを想定したものだと思うので、`me/project`で良いかも

他にも影響箇所あれば検討お願いします

**Comment by coord-e** [comment]
> me/project/listは複数あることを想定したものだと思うので、me/projectで良いかも

これは副責任者概念が実装されたら複数になるので、おそらく `me/project/list` のままです

**Comment by mkobayashime** [comment]
> これはメンバー概念が実装される可能性があり複数になりうるので、おそらく me/project/list のままです

承知

**Comment by coord-e** [comment]
とりあえず blocked by #17
